
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: May  5 2026 11:40:40 +07 (May  5 2026 04:40:40 UTC)

// Verification Directory fv/risc_cpu 

module controller(clk, rst, opcode, zero, sel, rd, ld_ir, halt, inc_pc,
     ld_ac, ld_pc, wr, data_e, _cdn, _cdn_1, _cdn_2);
  input clk, rst, zero;
  input [2:0] opcode;
  output sel, rd, ld_ir, halt, inc_pc, ld_ac, ld_pc, wr, data_e, _cdn,
       _cdn_1, _cdn_2;
  wire clk, rst, zero;
  wire [2:0] opcode;
  wire sel, rd, ld_ir, halt, inc_pc, ld_ac, ld_pc, wr, data_e, _cdn,
       _cdn_1, _cdn_2;
  wire n_0, n_1, n_5, n_6, n_10;
  assign _cdn_2 = 1'b0;
  INVXL g779(.A (n_6), .Y (halt));
  NOR2X1 g786__2398(.A (_cdn), .B (n_5), .Y (inc_pc));
  NAND2XL g787__5107(.A (_cdn), .B (_cdn_1), .Y (n_6));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_10), .Q (_cdn_1));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_1), .Q (_cdn));
  AOI21XL g800__4319(.A0 (_cdn), .A1 (n_6), .B0 (rst), .Y (n_1));
  INVXL g802(.A (_cdn), .Y (n_0));
  AOI21X1 g2(.A0 (n_5), .A1 (n_0), .B0 (rst), .Y (n_10));
  INVX1 g804(.A (_cdn_1), .Y (n_5));
endmodule

module risc_cpu(clk, rst, debug_pc, debug_acc, debug_ir, debug_state,
     debug_halt);
  input clk, rst;
  output [7:0] debug_pc, debug_acc, debug_ir;
  output [2:0] debug_state;
  output debug_halt;
  wire clk, rst;
  wire [7:0] debug_pc, debug_acc, debug_ir;
  wire [2:0] debug_state;
  wire debug_halt;
  wire [2:0] \ctrl.state ;
  wire UNCONNECTED, UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2, data_e, inc_pc, ld_ac;
  wire ld_ir, mem_rd, mem_wr, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire sel;
  assign debug_state[0] = \ctrl.state [0];
  assign debug_state[1] = \ctrl.state [1];
  assign debug_state[2] = \ctrl.state [2];
  assign debug_ir[0] = 1'b0;
  assign debug_ir[1] = 1'b0;
  assign debug_ir[2] = 1'b0;
  assign debug_ir[3] = 1'b0;
  assign debug_ir[4] = 1'b0;
  assign debug_ir[5] = 1'b0;
  assign debug_ir[6] = 1'b0;
  assign debug_ir[7] = 1'b0;
  assign debug_acc[0] = 1'b0;
  assign debug_acc[1] = 1'b0;
  assign debug_acc[2] = 1'b0;
  assign debug_acc[3] = 1'b0;
  assign debug_acc[4] = 1'b0;
  assign debug_acc[5] = 1'b0;
  assign debug_acc[6] = 1'b0;
  assign debug_acc[7] = 1'b0;
  assign debug_pc[5] = 1'b0;
  assign debug_pc[6] = 1'b0;
  assign debug_pc[7] = 1'b0;
  controller ctrl(.clk (clk), .rst (rst), .opcode
       ({UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z}), .zero (UNCONNECTED_HIER_Z2), .sel (sel),
       .rd (mem_rd), .ld_ir (ld_ir), .halt (debug_halt), .inc_pc
       (inc_pc), .ld_ac (ld_ac), .ld_pc (UNCONNECTED), .wr (mem_wr),
       .data_e (data_e), ._cdn (\ctrl.state [0]), ._cdn_1
       (\ctrl.state [1]), ._cdn_2 (\ctrl.state [2]));
  DFFHQX1 \pc_count_reg[4] (.CK (clk), .D (n_12), .Q (debug_pc[4]));
  SDFFTRX1 \pc_count_reg[3] (.CK (clk), .D (n_6), .RN (debug_pc[2]),
       .SE (debug_pc[3]), .SI (n_10), .Q (debug_pc[3]), .QN (n_1));
  OAI2BB1X1 g1517__8428(.A0N (debug_pc[4]), .A1N (n_11), .B0 (n_9), .Y
       (n_12));
  SDFFQX1 \pc_count_reg[2] (.CK (clk), .D (n_6), .SE (debug_pc[2]), .SI
       (n_8), .Q (debug_pc[2]));
  SDFFTRX1 \pc_count_reg[1] (.CK (clk), .D (n_5), .RN (debug_pc[0]),
       .SE (debug_pc[1]), .SI (n_7), .Q (debug_pc[1]), .QN (n_2));
  AO21X1 g1520__5526(.A0 (n_1), .A1 (n_5), .B0 (n_10), .Y (n_11));
  AO21X1 g1521__6783(.A0 (n_0), .A1 (n_5), .B0 (n_8), .Y (n_10));
  NAND4BXL g1522__3680(.AN (debug_pc[4]), .B (debug_pc[2]), .C
       (debug_pc[3]), .D (n_6), .Y (n_9));
  SDFFQX1 \pc_count_reg[0] (.CK (clk), .D (n_5), .SE (debug_pc[0]), .SI
       (n_4), .Q (debug_pc[0]));
  AO21X1 g1524__1617(.A0 (n_2), .A1 (n_5), .B0 (n_7), .Y (n_8));
  AO21X1 g1525__2802(.A0 (n_3), .A1 (n_5), .B0 (n_4), .Y (n_7));
  AND3XL g1526__1705(.A (debug_pc[1]), .B (debug_pc[0]), .C (n_5), .Y
       (n_6));
  NOR2BX1 g1527__5122(.AN (inc_pc), .B (rst), .Y (n_5));
  NOR2XL g1528__8246(.A (rst), .B (inc_pc), .Y (n_4));
  INVX1 g1534(.A (debug_pc[2]), .Y (n_0));
  INVX1 g1536(.A (debug_pc[0]), .Y (n_3));
endmodule

